test_tests_2015: test_tests_2015_Day_01 $\
				 test_tests_2015_Day_02 $\
				 test_tests_2015_Day_03 $\
				 test_tests_2015_Day_05 $\
				 test_tests_2015_Day_06 $\
				 test_tests_2015_Day_08 $\
				 test_tests_2015_Day_10 $\
				 test_tests_2015_Day_11

include test/tests/2015/Day_01/makefile
include test/tests/2015/Day_02/makefile
include test/tests/2015/Day_03/makefile
include test/tests/2015/Day_05/makefile
include test/tests/2015/Day_06/makefile
include test/tests/2015/Day_08/makefile
include test/tests/2015/Day_10/makefile
include test/tests/2015/Day_11/makefile

build/test/executable/2015: | build/test/executable
	mkdir "$@"

build/test/object/tests/2015: | build/test/object/tests
	mkdir "$@"